---
development:
  enhance_image_tag: true
  static_image_support: false
production:
  enhance_image_tag: true
  static_image_support: true
test:
  enhance_image_tag: true
  static_image_support: false
