# Settings.app_name
debug: true

# meta
app_name: 'まとめェ・・・'
app_description: 'まとめェ・・・は2ちゃんねるのまとめのリンクを集めたアンテナサイトです。'
app_keyword: 'まとめ, 2ch, 2ちゃんねる'

# twitter
# Settings.twitter_consumer_key, Settings.twitter_consumer_secret
twitter_consumer_key: 'HoVXZinoHPmvO30ItQx8jg'
twitter_consumer_secret: 'HvAeUcpotCwgnRSlzaSXc2gRfxNjOgM4VrXY2cF94Qo'

